[package]
name = "session-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
sniffer-rs = "1.1.2"
tigris-rs = { path = "/home/lighttigerxiv/projects/whiskers-apps/tigris-rs", features = [
    "extension",
] }
