[package]
name = "session-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
sniffer-rs = "1.1.2"
tigris-core = { path = "/home/lighttigerxiv/dev/whiskers-apps/pc/tigris-core/", features = [
    "extension",
] }
